networks:
  default:
    external: true
    name: ${NETWORK_NAME}

services:
  metabase:
    build:
      context: .
      dockerfile: Dockerfile.metabase
    ports:
      - "${METABASE_PORT}:3000"
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    depends_on:
      - metabase_db
    environment:
      MB_DB_TYPE: postgres
      MB_DB_HOST: metabase_db
      MB_DB_PORT: 5432
      MB_DB_USER: ${METABASE_DB_NAME}
      MB_DB_PASS: ${METABASE_DB_PASSWORD}
      MB_DB_NAME: ${METABASE_DB_USER}
  
  metabase_db:
    image: postgres:15.3-alpine
    restart: unless-stopped
    volumes:
      - metabase-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${METABASE_DB_USER}
      POSTGRES_PASSWORD: ${METABASE_DB_PASSWORD}
      POSTGRES_DB: ${METABASE_DB_NAME}
    ports:
      - "127.0.0.1:${METABASE_DB_PORT}:5432"

volumes:
  metabase-data:
    driver: local
    driver_opts:
      type: none
      device: ${METABASE_DB_PERSIST_PATH}
      o: bind