version: "3.8"

services:
  metabase:
    image: metabase/metabase:latest
    platform: linux/amd64
    ports:
      - "${METABASE_PORT}:3000"
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${POSTGRES_DB}
      MB_DB_PORT: ${DB_PORT}
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: host.docker.internal
    
    volumes:
      - metabase-data:/metabase-data

volumes:
  metabase-data:
    driver: local
    driver_opts:
      type: none
      device: ${METABASE_PERSIST_PATH}
      o: bind