version: '3.8'
services:
  metabase:
    image: stephaneturquay/metabase-arm64:latest
    ports:
      - "6000:${PORT:-3000}"
    environment:
      MB_JETTY_PORT: "${PORT:-3000}"
      MB_DB_TYPE: "${DB_TYPE:-postgres}"
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: myuser
      MB_DB_PASS: mypassword
      MB_DB_HOST: db
    depends_on:
      - db

  db:
    image: postgres:latest
    # ports:
    #   - "9432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: metabaseappdb
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data

# volumes:
#   postgres-data:
