networks:
  default:
    external: true
    name: ${NETWORK_NAME}

services:
  metabase:
    build:
      context: .
      dockerfile: Dockerfile.metabase
    ports:
      - "${METABASE_PORT}:3000"
    volumes:
      - /dev/urandom:/dev/random:ro
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    depends_on:
      - metabase_db
    environment:
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: ${METABASE_DB_NAME}
      MB_DB_PORT: 3306
      MB_DB_HOST: metabase_db
      MB_DB_USER: ${METABASE_DB_USER}
      MB_DB_PASS: ${METABASE_DB_PASSWORD}
      # MB_DB_AUTOMIGRATE: false
      # MB_DB_CONNECTION_URI: "jdbc:postgresql://metabase_db:7432/${METABASE_DB_NAME}?currentSchema=public"
      
      

  
  metabase_db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${METABASE_DB_PASSWORD}
      MYSQL_DATABASE: ${METABASE_DB_NAME}
      MYSQL_USER: ${METABASE_DB_USER}
      MYSQL_PASSWORD: ${METABASE_DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    # command: >
    #   postgres
    #   -p 7432
    #   -c shared_buffers=512MB
    #   -c work_mem=32MB
    #   -c maintenance_work_mem=128MB
    #   -c max_connections=100
    #   -c effective_cache_size=1GB
    #   -c statement_timeout=60000
    #   -c idle_in_transaction_session_timeout=60000
    # ports:
    #   - "127.0.0.1:${METABASE_DB_PORT}:7432"

# volumes:
#   metabase-data:
#     driver: local
#     driver_opts:
#       type: none
#       device: ${METABASE_DB_PERSIST_PATH}
#       o: bind