version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build-and-deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - setup_remote_docker:
          version: default
          docker_layer_caching: true

      - add_ssh_keys:
          fingerprints:
            - "SHA256:4X9nkRG1kXfKre1B+w9dJhzMltIQni947mNoV+qyCpI"

      - run:
          name: Install Node & pnpm
          command: |
            curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
            apt-get install -y nodejs
            npm install -g pnpm@8.6.11

      - run:
          name: Install Dependencies
          command: pnpm install

      - run:
          name: Generate Prisma Client
          command: pnpm prisma generate

      - run:
          name: Run Database Migrations
          command: |
            export DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:1111/${POSTGRES_DB}
            ssh -fN -L 1111:localhost:${DB_PORT} -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_IP -p $SERVER_PORT 2>&1
            pnpm run migrate:deploy

      - run:
          name: Enable Buildx and QEMU for ARM builds
          command: |
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker buildx create --use --name multiarch-builder
            docker buildx inspect --bootstrap

      - run:
          name: Build and Push Docker Image
          command: |
            echo $DOCKERHUB_TOKEN | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker buildx build \
              --platform linux/arm64 \
              --tag ${DOCKERHUB_USERNAME}/optinetflow:${CIRCLE_SHA1} \
              --tag ${DOCKERHUB_USERNAME}/optinetflow:latest \
              --build-arg PORT=${PORT} \
              --push \
              .
            docker logout

      - run:
          name: Deploy to Server
          command: |
            export TEMP_ENV_PATH=/home/ubuntu/temp-backend-env
            echo "$ENV_FILE" > .env
            ssh -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_IP -p $SERVER_PORT "echo $DOCKERHUB_TOKEN | docker login --username $DOCKERHUB_USERNAME --password-stdin && mkdir -p $TEMP_ENV_PATH"
            ssh -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_IP -p $SERVER_PORT "docker pull ${DOCKERHUB_USERNAME}/optinetflow:${CIRCLE_SHA1}"
            ssh -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_IP -p $SERVER_PORT "docker container rm -f $CONTAINER_NAME || true"
            scp -o StrictHostKeyChecking=no -P $SERVER_PORT .env $SERVER_USERNAME@$SERVER_IP:$TEMP_ENV_PATH
            ssh -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_IP -p $SERVER_PORT "docker run -d --name $CONTAINER_NAME --env-file $TEMP_ENV_PATH/.env --network=${NETWORK_NAME} --restart always ${DOCKERHUB_USERNAME}/optinetflow:${CIRCLE_SHA1}"
            ssh -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_IP -p $SERVER_PORT "docker logout"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - main
                - dev
